package com.qa.verifyroleacess.tests;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.qa.verifyroleaccess.base.roleaccessBaseTest;

public class SchoolManagementSchoolERPtest extends roleaccessBaseTest {
	
	@BeforeClass
	
	public void DashboadPageSetup() {
		dataSheetName = "CADMINSMMmodule";
//		dataSheetName = "SchoolERPAdminSMMmodule";
//		dataSheetName = "SchoolAccountsHeadSMMmodule";
//		dataSheetName = "LibrarianSMMmodule";
//		dataSheetName = "PrincipalSMMmodule";
//		dataSheetName = "VicePrincipalSMMmodule";
//		dataSheetName = "NiyogaaFinanceHeadSMMmodule";
//		dataSheetName = "NiyogaaMarketinHeadSMMmodule";
//		dataSheetName = "NiyogaaAdministrationHeadSMMmodule";
		
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("SchoolERPAdminusername"), prop.getProperty("SchoolERPAdminpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("SchoolAccountHeadusername"), prop.getProperty("SchoolAccountHeadpassword"));
		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("CADMINusername"), prop.getProperty("CADMINpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("Librarianusername"), prop.getProperty("Librarianpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("Principalusername"), prop.getProperty("Principalpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("VicePrincipalusername"), prop.getProperty("VicePrincipalpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("NiyogaaMarketingHeadusername"), prop.getProperty("NiyogaaMarketingHeadpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("NiyogaaAdministartionHeadusername"), prop.getProperty("NiyogaaAdministartionHeadpassword"));
//		SchoolManagementmodulepages = loginpage1.dousersSMMLogin(prop.getProperty("NiyogaaFinanceHeadusername"), prop.getProperty("NiyogaaFinanceHeadpassword"));

	}
	
	
	@Test(priority = 1,dataProvider="getdata") 
	  public void  SchoolERPLoginSchoolManagementreadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) {
		SchoolManagementmodulepages.verifySMMMainmenu(SMMMenu, SMMRead);
		  
	  }
	 @Test(priority = 2,dataProvider="getdata") 
	  public void SchoolERPLoginClassTeacherAllocationReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuRead(CTASubMenu, CTASubMenuRead);
	  
	  }
	 
	 @Test(priority = 3,dataProvider="getdata") 
	  public void SchoolERPLoginClassTeacherAllocationCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuCreate(CTASubMenuCreate);
	 
	  }
	 @Test(priority = 4,dataProvider="getdata") 
	  public void SchoolERPLoginClassTeacherAllocationEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuEdit(CTASubMenuEdit);
	  
	  }
	 @Test(priority = 5,dataProvider="getdata") 
	  public void SchoolERPLoginClassTeacherAllocationDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuDelete(CTASubMenuDelete);
	  
	  }
	 @Test(priority = 6,dataProvider="getdata",enabled=false) 
	  public void SchoolERPLoginAttendanceCalendarReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyAttCalsubmenuRead(AttCalSubMenu, AttCalSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 7,dataProvider="getdata",enabled=false) 
	  public void SchoolERPLoginAttendanceCalendarCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuCreate(AttCalSubMenuCreate);
	 
	  }
	 @Test(priority = 8,dataProvider="getdata",enabled=false) 
	  public void SchoolERPLoginAttendanceCalendarEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuEdit(AttCalSubMenuEdit);
	  
	  }
	 @Test(priority = 9,dataProvider="getdata",enabled=false) 
	  public void SchoolERPLoginAttendanceCalendarDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCTAsubmenuDelete(AttCalSubMenuDelete);
	  
	  }
	 @Test(priority = 10,dataProvider="getdata") 
	  public void SchoolERPLoginGradeCreationReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyGradeCreatsubmenuRead(GradeCreatSubMenu, GradeCreatSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 11,dataProvider="getdata") 
	  public void SchoolERPLoginGradeCreationCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyGradeCreatsubmenuCreate(GradeCreatSubMenuCreate);
	 
	  }
	 @Test(priority = 12,dataProvider="getdata") 
	  public void SchoolERPLoginGradeCreationEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyGradeCreatsubmenuEdit(GradeCreatSubMenuEdit);
	  
	  }
	 @Test(priority = 13,dataProvider="getdata") 
	  public void SchoolERPLoginGradeCreationDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyGradeCreatsubmenuDelete(GradeCreatSubMenuDelete, GradeCreatSubMenuRead);
	  
	  }
	 @Test(priority = 14,dataProvider="getdata") 
	  public void SchoolERPLoginSectionCreationReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifySectCreatsubmenuRead(SectCreatSubMenu, SectCreatSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 15,dataProvider="getdata") 
	  public void SchoolERPLoginSectionCreationCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifySectCreatsubmenuCreate(SectCreatSubMenuCreate);
	 
	  }
	 @Test(priority = 16,dataProvider="getdata") 
	  public void SchoolERPLoginSectionCreationEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifySectCreatsubmenuEdit(SectCreatSubMenuEdit);
	  
	  }
	 @Test(priority = 17,dataProvider="getdata") 
	  public void SchoolERPLoginSectionCreationDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifySectCreatsubmenuDelete(SectCreatSubMenuDelete, SectCreatSubMenuRead);
	  
	  }
	 @Test(priority = 18,dataProvider="getdata") 
	  public void SchoolERPLoginHouseManagementReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyHMsubmenuRead(HMSubMenu, HMSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 19,dataProvider="getdata") 
	  public void SchoolERPLoginHouseManagementCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyHMsubmenuCreate(HMSubMenuCreate);
	 
	  }
	 @Test(priority = 20,dataProvider="getdata") 
	  public void SchoolERPLoginHouseManagementEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyHMsubmenuEdit(HMSubMenuEdit);
	  
	  }
	 @Test(priority = 21,dataProvider="getdata") 
	  public void SchoolERPLoginHouseManagementDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyHMsubmenuDelete(HMSubMenuDelete);
	  
	  }
	 //Environment read.
	 @Test(priority = 22,dataProvider="getdata") 
	  public void SchoolERPLoginEnvironmentReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyENVMainmenu(EnvSubMenu, EnvSubMenuRead);
	  
	  }
	 @Test(priority = 23,dataProvider="getdata") 
	  public void SchoolERPLoginCreateEnvironmentReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCEsubmenuRead(CEnvSubMenu, CEnvSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 24,dataProvider="getdata") 
	  public void SchoolERPLoginCreateEnvironmentCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCEsubmenuCreate(CEnvSubMenuCreate);
	 
	  }
	 @Test(priority = 25,dataProvider="getdata") 
	  public void SchoolERPLoginCreateEnvironmentEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCEsubmenuEdit(CEnvSubMenuEdit);
	  
	  }
	 @Test(priority = 26,dataProvider="getdata") 
	  public void SchoolERPLoginCreateEnvironmentDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyCEsubmenuDelete(CEnvSubMenuDelete);
	  
	  }
	 
	 //Business stage setup
	 @Test(priority = 27,dataProvider="getdata") 
	  public void SchoolERPLoginCreateBSSetupReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyBSSetupCreatsubmenuRead(BSSSubMenu, BSSSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 28,dataProvider="getdata") 
	  public void SchoolERPLoginCreateBSSetupCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyBSSetupCreatsubmenuCreate(BSSSubMenuCreate, BSSSubMenuRead);
	 
	  }
	 @Test(priority = 29,dataProvider="getdata") 
	  public void SchoolERPLoginCreateBSSetupEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyBSSetupCreatsubmenuEdit(BSSSubMenuEdit, BSSSubMenuRead);
	  
	  }
	 @Test(priority = 30,dataProvider="getdata") 
	  public void SchoolERPLoginCreateBSSetupDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyBSSetupCreatsubmenuDelete(BSSSubMenuDelete, BSSSubMenuRead);
	  
	  }

	 //Optional Subject
	 
	 @Test(priority = 31,dataProvider="getdata") 
	  public void SchoolERPLoginOptionalSubjectReadTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyOptionalSubjectCreatsubmenuRead(OSSubMenu, OSSubMenuRead);;
	  
	  }
	 
	 @Test(priority = 32,dataProvider="getdata") 
	  public void SchoolERPLoginOptionalSubjectCreateverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyOptionalSubjectCreatsubmenuCreate(OSSubMenuCreate, OSSubMenuRead);
	 
	  }
	 @Test(priority = 33,dataProvider="getdata") 
	  public void SchoolERPLoginOptionalSubjectEditverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyOptionalSubjectCreatsubmenuEdit(OSSubMenuEdit, OSSubMenuRead);
	  
	  }
	 @Test(priority = 34,dataProvider="getdata") 
	  public void SchoolERPLoginOptionalSubjectDeleteverifyTest(String SMMMenu,String SMMRead,String CTASubMenu,String CTASubMenuRead,String CTASubMenuCreate,String CTASubMenuEdit,String CTASubMenuDelete,String AttCalSubMenu,String AttCalSubMenuRead,String AttCalSubMenuCreate,String AttCalSubMenuEdit,String AttCalSubMenuDelete,String GradeCreatSubMenu,String GradeCreatSubMenuRead,String GradeCreatSubMenuCreate,String GradeCreatSubMenuEdit,String GradeCreatSubMenuDelete,String SectCreatSubMenu,String SectCreatSubMenuRead,String SectCreatSubMenuCreate,String SectCreatSubMenuEdit,String SectCreatSubMenuDelete,String HMSubMenu,String HMSubMenuRead,String HMSubMenuCreate,String HMSubMenuEdit,String HMSubMenuDelete,String OSSubMenu,String OSSubMenuRead,String OSSubMenuCreate,String OSSubMenuEdit,String OSSubMenuDelete,String BSSSubMenu,String BSSSubMenuRead,String BSSSubMenuCreate,String BSSSubMenuEdit,String BSSSubMenuDelete,String SCSubMenu,String SCSubMenuRead,String SCSubMenuCreate,String SCSubMenuEdit,String SCSubMenuDelete,String EnvSubMenu,String EnvSubMenuRead,String CEnvSubMenu,String CEnvSubMenuRead,String CEnvSubMenuCreate,String CEnvSubMenuEdit,String CEnvSubMenuDelete) { 
		 SchoolManagementmodulepages.verifyOptionalSubjectCreatsubmenuDelete(OSSubMenuDelete, OSSubMenuRead);
	  
	  }
	 
}
